-- location insertions
insert into location (street, locality, city, state, pincode) values ('3 Graceland Street', 'Linden', 'New Delhi', 'Delhi', 110010);
insert into location (street, locality, city, state, pincode) values ('046 Sycamore Avenue', 'Thackeray', 'New Delhi', 'Delhi', 110064);
insert into location (street, locality, city, state, pincode) values ('1972 Dennis Junction', 'Oneill', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('39 Bluejay Terrace', 'Monument', 'New Delhi', 'Delhi', 110068);
insert into location (street, locality, city, state, pincode) values ('50080 Dapin Road', 'Elmside', 'New Delhi', 'Delhi', 110012);
insert into location (street, locality, city, state, pincode) values ('0 Northland Plaza', 'Rieder', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('1040 Dennis Way', 'Sachs', 'New Delhi', 'Delhi', 110032);
insert into location (street, locality, city, state, pincode) values ('099 Myrtle Junction', 'Eggendart', 'New Delhi', 'Delhi', 110031);
insert into location (street, locality, city, state, pincode) values ('4202 Dexter Junction', 'Glacier Hill', 'New Delhi', 'Delhi', 110038);
insert into location (street, locality, city, state, pincode) values ('68158 Anniversary Terrace', 'Kedzie', 'New Delhi', 'Delhi', 110030);
insert into location (street, locality, city, state, pincode) values ('30 Oneill Place', 'Mandrake', 'New Delhi', 'Delhi', 110019);
insert into location (street, locality, city, state, pincode) values ('0861 Victoria Court', 'Heath', 'New Delhi', 'Delhi', 110046);
insert into location (street, locality, city, state, pincode) values ('1 Transport Junction', 'Summit', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('52334 Glacier Hill Avenue', 'Eliot', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('50617 Roth Point', 'Sloan', 'New Delhi', 'Delhi', 110004);
insert into location (street, locality, city, state, pincode) values ('2864 Green Plaza', 'Alpine', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('61700 Fisk Alley', 'Main', 'New Delhi', 'Delhi', 110005);
insert into location (street, locality, city, state, pincode) values ('754 Killdeer Pass', 'Blaine', 'New Delhi', 'Delhi', 110032);
insert into location (street, locality, city, state, pincode) values ('835 Merry Drive', 'Delaware', 'New Delhi', 'Delhi', 110046);
insert into location (street, locality, city, state, pincode) values ('502 Messerschmidt Junction', 'Mosinee', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('8 Jackson Court', 'Hovde', 'New Delhi', 'Delhi', 110004);
insert into location (street, locality, city, state, pincode) values ('837 Blaine Court', 'Sauthoff', 'New Delhi', 'Delhi', 110018);
insert into location (street, locality, city, state, pincode) values ('0569 Barnett Drive', '7th', 'New Delhi', 'Delhi', 110067);
insert into location (street, locality, city, state, pincode) values ('0 North Street', 'Northland', 'New Delhi', 'Delhi', 110014);
insert into location (street, locality, city, state, pincode) values ('31400 Warrior Avenue', 'Birchwood', 'New Delhi', 'Delhi', 110034);
insert into location (street, locality, city, state, pincode) values ('8203 Namekagon Place', 'Magdeline', 'New Delhi', 'Delhi', 110049);
insert into location (street, locality, city, state, pincode) values ('79609 Randy Point', 'Talmadge', 'New Delhi', 'Delhi', 110019);
insert into location (street, locality, city, state, pincode) values ('68 Reinke Drive', 'Saint Paul', 'New Delhi', 'Delhi', 110026);
insert into location (street, locality, city, state, pincode) values ('90159 Stoughton Drive', 'Stoughton', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('9 School Road', 'American Ash', 'New Delhi', 'Delhi', 110068);
insert into location (street, locality, city, state, pincode) values ('55278 Victoria Parkway', 'Caliangt', 'New Delhi', 'Delhi', 110048);
insert into location (street, locality, city, state, pincode) values ('7 American Ash Hill', 'Lerdahl', 'New Delhi', 'Delhi', 110056);
insert into location (street, locality, city, state, pincode) values ('4 Bobwhite Terrace', 'Corry', 'New Delhi', 'Delhi', 110033);
insert into location (street, locality, city, state, pincode) values ('180 Sycamore Plaza', 'Bultman', 'New Delhi', 'Delhi', 110003);
insert into location (street, locality, city, state, pincode) values ('3 Logan Pass', 'Fisk', 'New Delhi', 'Delhi', 110041);
insert into location (street, locality, city, state, pincode) values ('41529 Union Way', 'Parkside', 'New Delhi', 'Delhi', 110052);
insert into location (street, locality, city, state, pincode) values ('30 Waubesa Avenue', 'Sherman', 'New Delhi', 'Delhi', 110058);
insert into location (street, locality, city, state, pincode) values ('06 Sachtjen Place', 'Sommers', 'New Delhi', 'Delhi', 110026);
insert into location (street, locality, city, state, pincode) values ('132 Bartelt Way', 'Sunbrook', 'New Delhi', 'Delhi', 110042);
insert into location (street, locality, city, state, pincode) values ('1998 Susan Junction', 'Hovde', 'New Delhi', 'Delhi', 110004);
insert into location (street, locality, city, state, pincode) values ('10072 Banding Way', 'Elmside', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('30095 Havey Plaza', '7th', 'New Delhi', 'Delhi', 110065);
insert into location (street, locality, city, state, pincode) values ('8 Weeping Birch Avenue', 'Upham', 'New Delhi', 'Delhi', 110042);
insert into location (street, locality, city, state, pincode) values ('36591 Hovde Street', 'Iowa', 'New Delhi', 'Delhi', 110005);
insert into location (street, locality, city, state, pincode) values ('089 Calypso Terrace', 'Service', 'New Delhi', 'Delhi', 110066);
insert into location (street, locality, city, state, pincode) values ('0 Anhalt Trail', 'Gulseth', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('5 Weeping Birch Pass', 'Schiller', 'New Delhi', 'Delhi', 110047);
insert into location (street, locality, city, state, pincode) values ('209 Pepper Wood Way', 'Westridge', 'New Delhi', 'Delhi', 110012);
insert into location (street, locality, city, state, pincode) values ('80591 Eagan Alley', 'Ilene', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('7 Norway Maple Crossing', 'Nobel', 'New Delhi', 'Delhi', 110061);
insert into location (street, locality, city, state, pincode) values ('64 Miller Pass', 'North', 'New Delhi', 'Delhi', 110068);
insert into location (street, locality, city, state, pincode) values ('43483 Nancy Park', 'Moulton', 'New Delhi', 'Delhi', 110018);
insert into location (street, locality, city, state, pincode) values ('005 Sommers Crossing', 'Debra', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('5 Beilfuss Court', 'Fuller', 'New Delhi', 'Delhi', 110038);
insert into location (street, locality, city, state, pincode) values ('41165 Crest Line Alley', 'Hauk', 'New Delhi', 'Delhi', 110061);
insert into location (street, locality, city, state, pincode) values ('6122 Twin Pines Drive', 'Kings', 'New Delhi', 'Delhi', 110013);
insert into location (street, locality, city, state, pincode) values ('2 Barnett Crossing', 'Mifflin', 'New Delhi', 'Delhi', 110020);
insert into location (street, locality, city, state, pincode) values ('2 Moose Place', 'Macpherson', 'New Delhi', 'Delhi', 110052);
insert into location (street, locality, city, state, pincode) values ('5 Raven Drive', 'Utah', 'New Delhi', 'Delhi', 110049);
insert into location (street, locality, city, state, pincode) values ('9 Park Meadow Hill', 'Manufacturers', 'New Delhi', 'Delhi', 110003);
insert into location (street, locality, city, state, pincode) values ('96795 Kedzie Lane', 'Lukken', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('9 Grover Court', 'Granby', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('627 Mariners Cove Terrace', 'Judy', 'New Delhi', 'Delhi', 110063);
insert into location (street, locality, city, state, pincode) values ('669 Cambridge Parkway', 'Pankratz', 'New Delhi', 'Delhi', 110016);
insert into location (street, locality, city, state, pincode) values ('0727 Valley Edge Junction', 'Merry', 'New Delhi', 'Delhi', 110043);
insert into location (street, locality, city, state, pincode) values ('60434 Golf Course Pass', 'Blue Bill Park', 'New Delhi', 'Delhi', 110050);
insert into location (street, locality, city, state, pincode) values ('9875 Summerview Drive', 'Fairview', 'New Delhi', 'Delhi', 110025);
insert into location (street, locality, city, state, pincode) values ('7528 Goodland Alley', 'Messerschmidt', 'New Delhi', 'Delhi', 110025);
insert into location (street, locality, city, state, pincode) values ('0 Corry Plaza', 'Fulton', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('52999 Birchwood Way', 'Ilene', 'New Delhi', 'Delhi', 110011);
insert into location (street, locality, city, state, pincode) values ('9 Sunbrook Lane', 'Logan', 'New Delhi', 'Delhi', 110048);
insert into location (street, locality, city, state, pincode) values ('7 Luster Place', 'Ronald Regan', 'New Delhi', 'Delhi', 110032);
insert into location (street, locality, city, state, pincode) values ('975 Dryden Junction', '3rd', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('9347 Drewry Street', 'Evergreen', 'New Delhi', 'Delhi', 110045);
insert into location (street, locality, city, state, pincode) values ('01836 Basil Center', 'Merrick', 'New Delhi', 'Delhi', 110020);
insert into location (street, locality, city, state, pincode) values ('3042 Paget Crossing', 'Laurel', 'New Delhi', 'Delhi', 110007);
insert into location (street, locality, city, state, pincode) values ('02 Becker Crossing', 'Quincy', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('2 Shopko Place', '3rd', 'New Delhi', 'Delhi', 110046);
insert into location (street, locality, city, state, pincode) values ('91 Londonderry Pass', 'Hintze', 'New Delhi', 'Delhi', 110034);
insert into location (street, locality, city, state, pincode) values ('18545 Texas Point', 'David', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('991 Brickson Park Circle', 'Gulseth', 'New Delhi', 'Delhi', 110051);
insert into location (street, locality, city, state, pincode) values ('6 Doe Crossing Alley', 'Shoshone', 'New Delhi', 'Delhi', 110063);
insert into location (street, locality, city, state, pincode) values ('723 Charing Cross Point', 'Killdeer', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('555 David Trail', 'Iowa', 'New Delhi', 'Delhi', 110014);
insert into location (street, locality, city, state, pincode) values ('19 Judy Park', 'Linden', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('50 Union Parkway', 'Judy', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('1090 Fairfield Plaza', 'Crescent Oaks', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('8 Portage Plaza', 'Independence', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('08792 Evergreen Place', 'Union', 'New Delhi', 'Delhi', 110043);
insert into location (street, locality, city, state, pincode) values ('8517 Schurz Junction', 'Debra', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('54 Macpherson Junction', 'Thierer', 'New Delhi', 'Delhi', 110041);
insert into location (street, locality, city, state, pincode) values ('28 Pawling Drive', 'Gerald', 'New Delhi', 'Delhi', 110024);
insert into location (street, locality, city, state, pincode) values ('6 Glendale Drive', 'Talisman', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('1 Ludington Street', 'Waubesa', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('981 Park Meadow Park', 'Kings', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('26817 Northview Place', 'Main', 'New Delhi', 'Delhi', 110070);
insert into location (street, locality, city, state, pincode) values ('343 Crownhardt Circle', 'Crownhardt', 'New Delhi', 'Delhi', 110030);
insert into location (street, locality, city, state, pincode) values ('01534 Michigan Place', 'Center', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('51100 Crownhardt Junction', 'Porter', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);


insert into location (street, locality, city, state, pincode) values ('922 Declaration Place', 'Melvin', 'Mathura', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('841 Laurel Crossing', 'Orin', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220046);
insert into location (street, locality, city, state, pincode) values ('8 Glendale Center', 'Jackson', 'Agra', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('05 Evergreen Way', 'Everett', 'Meerut', 'Uttar Pradesh', 220022);
insert into location (street, locality, city, state, pincode) values ('8 Katie Road', 'Northridge', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220072);
insert into location (street, locality, city, state, pincode) values ('0829 Myrtle Crossing', 'Ramsey', 'Agra', 'Uttar Pradesh', 220020);
insert into location (street, locality, city, state, pincode) values ('8361 Packers Hill', 'Elgar', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('09167 Eagan Pass', 'Bunting', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220072);
insert into location (street, locality, city, state, pincode) values ('19377 Bonner Plaza', 'Marquette', 'Mathura', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('812 Drewry Junction', 'South', 'Mathura', 'Uttar Pradesh', 220047);
insert into location (street, locality, city, state, pincode) values ('0771 Mallory Park', 'Eggendart', 'Vrindavan', 'Uttar Pradesh', 220024);
insert into location (street, locality, city, state, pincode) values ('2132 Dennis Hill', 'Coolidge', 'Meerut', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('73719 Main Terrace', 'Boyd', 'Ghaziabad', 'Uttar Pradesh', 220015);
insert into location (street, locality, city, state, pincode) values ('6722 Bultman Road', 'Hoepker', 'Mathura', 'Uttar Pradesh', 220040);
insert into location (street, locality, city, state, pincode) values ('0 Florence Parkway', 'Shoshone', 'Vrindavan', 'Uttar Pradesh', 220077);
insert into location (street, locality, city, state, pincode) values ('48443 Summer Ridge Road', 'Fulton', 'Ghaziabad', 'Uttar Pradesh', 220079);
insert into location (street, locality, city, state, pincode) values ('0 Beilfuss Point', 'Ridge Oak', 'Vrindavan', 'Uttar Pradesh', 220050);
insert into location (street, locality, city, state, pincode) values ('1 8th Road', 'Springs', 'Meerut', 'Uttar Pradesh', 220021);
insert into location (street, locality, city, state, pincode) values ('42 Springs Street', 'Rigney', 'Ghaziabad', 'Uttar Pradesh', 220076);
insert into location (street, locality, city, state, pincode) values ('42448 Sachs Hill', 'Talmadge', 'Vrindavan', 'Uttar Pradesh', 220014);
insert into location (street, locality, city, state, pincode) values ('57412 Debs Circle', 'Crowley', 'Ghaziabad', 'Uttar Pradesh', 220009);
insert into location (street, locality, city, state, pincode) values ('434 Hayes Avenue', 'Mallard', 'Mathura', 'Uttar Pradesh', 220055);
insert into location (street, locality, city, state, pincode) values ('203 Sachtjen Crossing', 'Merrick', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220072);
insert into location (street, locality, city, state, pincode) values ('9 Monica Road', 'Dwight', 'Mathura', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('7786 Debra Crossing', 'Lakewood Gardens', 'Mathura', 'Uttar Pradesh', 220042);
insert into location (street, locality, city, state, pincode) values ('839 Sullivan Street', 'Mockingbird', 'Agra', 'Uttar Pradesh', 220015);
insert into location (street, locality, city, state, pincode) values ('4568 Menomonie Avenue', 'Morning', 'Meerut', 'Uttar Pradesh', 220011);
insert into location (street, locality, city, state, pincode) values ('11 Oriole Crossing', 'Main', 'Meerut', 'Uttar Pradesh', 220048);
insert into location (street, locality, city, state, pincode) values ('52987 Mcguire Terrace', 'Fair Oaks', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220043);
insert into location (street, locality, city, state, pincode) values ('5 Namekagon Center', 'Veith', 'Vrindavan', 'Uttar Pradesh', 220040);
insert into location (street, locality, city, state, pincode) values ('0404 Messerschmidt Way', 'Summer Ridge', 'Mathura', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('5 Vernon Trail', 'Orin', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220005);
insert into location (street, locality, city, state, pincode) values ('17857 Morningstar Terrace', 'Brentwood', 'Ghaziabad', 'Uttar Pradesh', 220068);
insert into location (street, locality, city, state, pincode) values ('912 Waxwing Hill', 'Division', 'Meerut', 'Uttar Pradesh', 220018);
insert into location (street, locality, city, state, pincode) values ('398 Oriole Road', 'Basil', 'Vrindavan', 'Uttar Pradesh', 220036);
insert into location (street, locality, city, state, pincode) values ('6664 Heath Hill', 'Anzinger', 'Ghaziabad', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('4 Sommers Alley', 'Reinke', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('195 Holmberg Crossing', 'Hayes', 'Vrindavan', 'Uttar Pradesh', 220039);
insert into location (street, locality, city, state, pincode) values ('27732 Briar Crest Alley', 'Westerfield', 'Ghaziabad', 'Uttar Pradesh', 220007);
insert into location (street, locality, city, state, pincode) values ('375 Bultman Avenue', 'Rieder', 'Mathura', 'Uttar Pradesh', 220010);
insert into location (street, locality, city, state, pincode) values ('5992 Dovetail Circle', 'Oriole', 'Meerut', 'Uttar Pradesh', 220056);
insert into location (street, locality, city, state, pincode) values ('4 Sunbrook Point', 'Continental', 'Mathura', 'Uttar Pradesh', 220033);
insert into location (street, locality, city, state, pincode) values ('4551 Gateway Lane', 'Gina', 'Ghaziabad', 'Uttar Pradesh', 220035);
insert into location (street, locality, city, state, pincode) values ('32 Riverside Center', 'Morningstar', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220054);
insert into location (street, locality, city, state, pincode) values ('2 West Terrace', 'Roxbury', 'Meerut', 'Uttar Pradesh', 220071);
insert into location (street, locality, city, state, pincode) values ('44 Nobel Way', 'Atwood', 'Meerut', 'Uttar Pradesh', 220005);
insert into location (street, locality, city, state, pincode) values ('1 Anderson Court', 'American Ash', 'Meerut', 'Uttar Pradesh', 220030);
insert into location (street, locality, city, state, pincode) values ('6530 Merry Avenue', 'Loeprich', 'Agra', 'Uttar Pradesh', 220031);
insert into location (street, locality, city, state, pincode) values ('63860 Clarendon Center', 'Buhler', 'Vrindavan', 'Uttar Pradesh', 220010);
insert into location (street, locality, city, state, pincode) values ('97 Sheridan Hill', 'Westerfield', 'Meerut', 'Uttar Pradesh', 220030);
insert into location (street, locality, city, state, pincode) values ('2809 Schmedeman Avenue', 'Charing Cross', 'Ghaziabad', 'Uttar Pradesh', 220065);
insert into location (street, locality, city, state, pincode) values ('456 Moose Center', 'Blackbird', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220041);
insert into location (street, locality, city, state, pincode) values ('12 Stuart Point', 'Aberg', 'Mathura', 'Uttar Pradesh', 220078);
insert into location (street, locality, city, state, pincode) values ('5874 Dennis Terrace', 'Heffernan', 'Meerut', 'Uttar Pradesh', 220030);
insert into location (street, locality, city, state, pincode) values ('8025 Gale Way', 'Moulton', 'Meerut', 'Uttar Pradesh', 220006);
insert into location (street, locality, city, state, pincode) values ('97 Raven Drive', 'Ryan', 'Meerut', 'Uttar Pradesh', 220064);
insert into location (street, locality, city, state, pincode) values ('83 Morning Lane', 'Everett', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220018);
insert into location (street, locality, city, state, pincode) values ('6 Birchwood Junction', 'Nova', 'Agra', 'Uttar Pradesh', 220076);
insert into location (street, locality, city, state, pincode) values ('982 Algoma Plaza', 'Green Ridge', 'Vrindavan', 'Uttar Pradesh', 220040);
insert into location (street, locality, city, state, pincode) values ('23643 Schurz Drive', 'Saint Paul', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220032);
insert into location (street, locality, city, state, pincode) values ('26 Vahlen Trail', 'Michigan', 'Agra', 'Uttar Pradesh', 220060);
insert into location (street, locality, city, state, pincode) values ('34 Sunnyside Street', 'Farragut', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('63 Sundown Court', 'Veith', 'Mathura', 'Uttar Pradesh', 220007);
insert into location (street, locality, city, state, pincode) values ('16 Waxwing Place', 'Dwight', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('3 Mariners Cove Crossing', 'Hintze', 'Meerut', 'Uttar Pradesh', 220061);
insert into location (street, locality, city, state, pincode) values ('048 Browning Center', 'Arrowood', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220032);
insert into location (street, locality, city, state, pincode) values ('495 Badeau Crossing', 'Mallard', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('8 Shasta Lane', 'Scott', 'Ghaziabad', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('9 Brentwood Parkway', 'Lindbergh', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220058);
insert into location (street, locality, city, state, pincode) values ('5 Donald Drive', 'Kennedy', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220006);
insert into location (street, locality, city, state, pincode) values ('0 Jenna Point', 'Hallows', 'Ghaziabad', 'Uttar Pradesh', 220029);
insert into location (street, locality, city, state, pincode) values ('90604 Russell Alley', 'Badeau', 'Ghaziabad', 'Uttar Pradesh', 220068);
insert into location (street, locality, city, state, pincode) values ('69538 Helena Pass', 'Dwight', 'Mathura', 'Uttar Pradesh', 220056);
insert into location (street, locality, city, state, pincode) values ('2 Garrison Street', 'Gulseth', 'Agra', 'Uttar Pradesh', 220029);
insert into location (street, locality, city, state, pincode) values ('42 Wayridge Drive', 'Maryland', 'Ghaziabad', 'Uttar Pradesh', 220026);
insert into location (street, locality, city, state, pincode) values ('6 Hollow Ridge Way', 'Bellgrove', 'Ghaziabad', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('104 Loomis Plaza', 'Heath', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220037);
insert into location (street, locality, city, state, pincode) values ('9 Redwing Circle', 'Farwell', 'Meerut', 'Uttar Pradesh', 220058);
insert into location (street, locality, city, state, pincode) values ('69 Hermina Court', 'Hoard', 'Vrindavan', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('484 Ludington Circle', 'Sutherland', 'Agra', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('62595 Swallow Place', 'Marcy', 'Agra', 'Uttar Pradesh', 220049);
insert into location (street, locality, city, state, pincode) values ('6134 Northwestern Point', 'Shopko', 'Vrindavan', 'Uttar Pradesh', 220068);
insert into location (street, locality, city, state, pincode) values ('58974 Fieldstone Lane', 'Florence', 'Agra', 'Uttar Pradesh', 220044);
insert into location (street, locality, city, state, pincode) values ('78924 Bellgrove Avenue', 'Washington', 'Vrindavan', 'Uttar Pradesh', 220073);
insert into location (street, locality, city, state, pincode) values ('5142 Atwood Lane', 'Delaware', 'Meerut', 'Uttar Pradesh', 220062);
insert into location (street, locality, city, state, pincode) values ('31 Clyde Gallagher Park', 'West', 'Ghaziabad', 'Uttar Pradesh', 220051);
insert into location (street, locality, city, state, pincode) values ('20 Warbler Trail', 'Fairview', 'Vrindavan', 'Uttar Pradesh', 220003);
insert into location (street, locality, city, state, pincode) values ('5 Grim Drive', 'Elka', 'Vrindavan', 'Uttar Pradesh', 220065);
insert into location (street, locality, city, state, pincode) values ('79567 Melody Drive', 'Dorton', 'Agra', 'Uttar Pradesh', 220054);
insert into location (street, locality, city, state, pincode) values ('06 Old Gate Park', 'Hintze', 'Agra', 'Uttar Pradesh', 220034);
insert into location (street, locality, city, state, pincode) values ('28820 Ridgeway Alley', 'Granby', 'Mathura', 'Uttar Pradesh', 220035);
insert into location (street, locality, city, state, pincode) values ('38047 Amoth Crossing', 'Artisan', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220052);
insert into location (street, locality, city, state, pincode) values ('883 Northview Parkway', 'Anzinger', 'Mathura', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('664 Lyons Terrace', 'Ridgeview', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220065);
insert into location (street, locality, city, state, pincode) values ('921 Dayton Terrace', 'Bunker Hill', 'Vrindavan', 'Uttar Pradesh', 220012);
insert into location (street, locality, city, state, pincode) values ('937 Pierstorff Place', 'Troy', 'Ghaziabad', 'Uttar Pradesh', 220080);
insert into location (street, locality, city, state, pincode) values ('50 Summit Drive', 'Laurel', 'Meerut', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('0 Farwell Point', 'Del Mar', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220050);
insert into location (street, locality, city, state, pincode) values ('43220 Schlimgen Way', 'Carioca', 'Ghaziabad', 'Uttar Pradesh', 220043);
insert into location (street, locality, city, state, pincode) values ('20007 Dexter Drive', 'Kenwood', 'Mathura', 'Uttar Pradesh', 220079);






insert into location (street, locality, city, state, pincode) values ('18545 Texas Point', 'David', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('991 Brickson Park Circle', 'Gulseth', 'New Delhi', 'Delhi', 110051);
insert into location (street, locality, city, state, pincode) values ('6 Doe Crossing Alley', 'Shoshone', 'New Delhi', 'Delhi', 110063);
insert into location (street, locality, city, state, pincode) values ('723 Charing Cross Point', 'Killdeer', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('555 David Trail', 'Iowa', 'New Delhi', 'Delhi', 110014);
insert into location (street, locality, city, state, pincode) values ('19 Judy Park', 'Linden', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('50 Union Parkway', 'Judy', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('1090 Fairfield Plaza', 'Crescent Oaks', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('8 Portage Plaza', 'Independence', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('08792 Evergreen Place', 'Union', 'New Delhi', 'Delhi', 110043);
insert into location (street, locality, city, state, pincode) values ('8517 Schurz Junction', 'Debra', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('54 Macpherson Junction', 'Thierer', 'New Delhi', 'Delhi', 110041);
insert into location (street, locality, city, state, pincode) values ('28 Pawling Drive', 'Gerald', 'New Delhi', 'Delhi', 110024);
insert into location (street, locality, city, state, pincode) values ('6 Glendale Drive', 'Talisman', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('1 Ludington Street', 'Waubesa', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('981 Park Meadow Park', 'Kings', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('26817 Northview Place', 'Main', 'New Delhi', 'Delhi', 110070);
insert into location (street, locality, city, state, pincode) values ('343 Crownhardt Circle', 'Crownhardt', 'New Delhi', 'Delhi', 110030);
insert into location (street, locality, city, state, pincode) values ('01534 Michigan Place', 'Center', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('51100 Crownhardt Junction', 'Porter', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('01534 Michigan Place', 'Center', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('51100 Crownhardt Junction', 'Porter', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);




-- customers insertions

insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (209, 'Granny Shury', '03506247877', 'gshury0@blogspot.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (12, 'Anastassia Keoghane', '05078086181', 'akeoghane1@mediafire.com', 'Cash', 5);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (98, 'Filmore Robichon', '01267019868', 'frobichon2@elegantthemes.com', 'Ola Money', 129);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (144, 'Karalee Cruise', '06337349306', 'kcruise3@paypal.com', 'Cash', 218);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (159, 'Tomaso Fidge', '09154290833', 'tfidge4@comcast.net', 'Ola Money', 178);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (197, 'Dallas Lovewell', '09137261835', 'dlovewell5@mtv.com', 'Ola Money', 87);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (46, 'Stanly Jurick', '09373521774', 'sjurick6@w3.org', 'Ola Money', 50);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (96, 'Sonnnie Ping', '03345782634', 'sping7@networkadvertising.org', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (130, 'Rosabelle Teaze', '09037536727', 'rteaze8@engadget.com', 'Cash', 67);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (97, 'Farley Pietron', '06394895546', 'fpietron9@hexun.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (223, 'Abner Traher', '09169386684', 'atrahera@virginia.edu', 'Ola Money', 178);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (195, 'Kelsey Levane', '03669766978', 'klevaneb@thetimes.co.uk', 'Cash', 77);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (220, 'Maje Dunster', '01418979592', 'mdunsterc@auda.org.au', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (134, 'Norbert Cossom', '03911061905', 'ncossomd@toplist.cz', 'Cash', 190);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (65, 'Darwin Doige', '08715767798', 'ddoigee@kickstarter.com', 'Ola Money', 149);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (199, 'Ivette Strute', '03806615778', 'istrutef@netvibes.com', 'Cash', 14);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (59, 'Stephen Pesticcio', '03096703862', 'spesticciog@bloomberg.com', 'Ola Money', 151);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (182, 'Anson Nice', '06105436783', 'aniceh@ovh.net', 'Cash', 209);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (176, 'Fleurette Beaney', '07195415416', 'fbeaneyi@google.nl', 'Cash', 209);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (16, 'Teodor Jaffrey', '04355371108', 'tjaffreyj@sina.com.cn', 'Ola Money', 89);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (143, 'Gussie Dye', '05168524988', 'gdyek@elegantthemes.com', 'Cash', 119);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (166, 'Justinian De Bruijne', '02182120772', 'jdel@google.co.jp', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (45, 'Adelind Herety', '09243270984', 'aheretym@ucsd.edu', 'Cash', 187);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (143, 'Jordan Pirelli', '01102956633', 'jpirellin@about.me', 'Cash', 179);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (37, 'Ferne Minmagh', '06007687132', 'fminmagho@whitehouse.gov', 'Ola Money', 99);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (205, 'Donn Flanaghan', '05496769345', 'dflanaghanp@tumblr.com', 'Cash', 176);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (32, 'Myrtice Skouling', '05917900734', 'mskoulingq@xinhuanet.com', 'Cash', 33);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (168, 'Robin Bayley', '01164326202', 'rbayleyr@friendfeed.com', 'Cash', 101);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (39, 'Beau Feechan', '04963684474', 'bfeechans@nbcnews.com', 'Ola Money', 178);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (8, 'Marion Chilles', '07745289955', 'mchillest@upenn.edu', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (48, 'Channa Hutchence', '06867691083', 'chutchenceu@amazon.de', 'Cash', 127);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (111, 'Rikki Ferrieres', '04471422631', 'rferrieresv@t.co', 'Ola Money', 179);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (183, 'Reggis Dugmore', '02277601663', 'rdugmorew@biblegateway.com', 'Ola Money', 155);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (198, 'Florenza Turford', '03461573386', 'fturfordx@cbc.ca', 'Cash', 45);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (200, 'Josee Dodshun', '04986861948', 'jdodshuny@vistaprint.com', 'Ola Money', 29);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (146, 'Balduin Kenshole', '08808142232', 'bkensholez@usnews.com', 'Ola Money', 128);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (48, 'Natale Pedley', '08414147876', 'npedley10@drupal.org', 'Cash', 182);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (171, 'Hilton Gerty', '04769899703', 'hgerty11@columbia.edu', 'Cash', 100);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (208, 'Joshuah Melly', '02492383597', 'jmelly12@yelp.com', 'Ola Money', 140);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (104, 'Nichol Lucock', '06065933675', 'nlucock13@home.pl', 'Cash', 153);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (77, 'Giorgi Gobel', '04459218177', 'ggobel14@skype.com', 'Ola Money', 146);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (100, 'Tannie Wyllcock', '04123702864', 'twyllcock15@theguardian.com', 'Ola Money', 74);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (32, 'Jerrie Wabb', '05944365721', 'jwabb16@flavors.me', 'Ola Money', 197);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (170, 'Ira Took', '05889262225', 'itook17@nyu.edu', 'Ola Money', 25);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (150, 'Arlee Aykroyd', '07279091187', 'aaykroyd18@ameblo.jp', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (180, 'Kimberlyn Whitebrook', '01194555548', 'kwhitebrook19@desdev.cn', 'Ola Money', 43);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (150, 'Pearle Stealfox', '08187329079', 'pstealfox1a@friendfeed.com', 'Ola Money', 184);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (95, 'Bette Chape', '02888244623', 'bchape1b@gnu.org', 'Ola Money', 185);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (82, 'Atalanta Durtnel', '01667052407', 'adurtnel1c@latimes.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (1, 'Dallis Berthomieu', '06488896077', 'dberthomieu1d@cloudflare.com', 'Ola Money', 149);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (75, 'Konstance Asquez', '06875037650', 'kasquez1e@blogger.com', 'Ola Money', 108);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (60, 'Layton Eddicott', '08968572611', 'leddicott1f@sourceforge.net', 'Ola Money', 143);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (202, 'Gwendolen Hegge', '05477258061', 'ghegge1g@google.fr', 'Ola Money', 163);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (197, 'Nichole Ainslee', '08015131793', 'nainslee1h@nbcnews.com', 'Cash', 62);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (3, 'Oralla Loads', '05526602969', 'oloads1i@google.pl', 'Ola Money', 181);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (15, 'Gawen Bayley', '08133793903', 'gbayley1j@typepad.com', 'Cash', 209);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (29, 'Marshall Castellaccio', '09195358476', 'mcastellaccio1k@si.edu', 'Cash', 220);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (198, 'Patsy Heathfield', '06877482322', 'pheathfield1l@nymag.com', 'Cash', 170);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (170, 'Eolande Rijkeseis', '09195068047', 'erijkeseis1m@joomla.org', 'Cash', 59);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (221, 'Donnie Mead', '04013516155', 'dmead1n@diigo.com', 'Cash', 115);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (224, 'Briggs Canet', '07602748694', 'bcanet1o@123-reg.co.uk', 'Ola Money', 78);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (87, 'Standford Lympenie', '03268660155', 'slympenie1p@boston.com', 'Ola Money', 185);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (11, 'Amalle Naish', '01776607915', 'anaish1q@parallels.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (188, 'Chris McCray', '07831569850', 'cmccray1r@blog.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (58, 'Jolene Esson', '07225629644', 'jesson1s@army.mil', 'Cash', 124);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (157, 'Billy Ralling', '02722295438', 'bralling1t@prnewswire.com', 'Cash', 61);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (28, 'Jeno Isakovic', '08716306824', 'jisakovic1u@hubpages.com', 'Cash', 191);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (206, 'Avram Brookwood', '09962178366', 'abrookwood1v@ocn.ne.jp', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (38, 'Tammie Alf', '03151989572', 'talf1w@amazon.com', 'Ola Money', 147);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (76, 'Ewart MacMeekan', '01351889482', 'emacmeekan1x@cnn.com', 'Cash', 175);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (52, 'Marianne Learmouth', '07054414145', 'mlearmouth1y@spiegel.de', 'Cash', 53);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (119, 'Cy Bielfelt', '06957332531', 'cbielfelt1z@reverbnation.com', 'Cash', 47);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (193, 'Janice Buessen', '06749495940', 'jbuessen20@bandcamp.com', 'Ola Money', 59);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (8, 'Esther Guerin', '08258270014', 'eguerin21@cbslocal.com', 'Cash', 133);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (188, 'Dannie Patley', '01374127548', 'dpatley22@go.com', 'Ola Money', 99);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (141, 'Edouard Lloyds', '09493497244', 'elloyds23@un.org', 'Ola Money', 49);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (2, 'Trixi Casarini', '04507736893', 'tcasarini24@taobao.com', 'Cash', 94);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (63, 'Armand McNeilly', '07068811351', 'amcneilly25@canalblog.com', 'Ola Money', 214);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (55, 'Pinchas Bilsland', '05531320846', 'pbilsland26@pcworld.com', 'Cash', 182);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (139, 'Danyelle Malec', '05267997145', 'dmalec27@163.com', 'Ola Money', 30);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (82, 'Torin Rodolphe', '06211859223', 'trodolphe28@mapquest.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (19, 'Deloris Vauter', '07835005900', 'dvauter29@telegraph.co.uk', 'Cash', 9);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (30, 'Harbert Lemin', '03673299535', 'hlemin2a@devhub.com', 'Ola Money', 42);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (75, 'Vic Hannibal', '06334691808', 'vhannibal2b@spotify.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (167, 'Tine Ebrall', '06985601181', 'tebrall2c@ucla.edu', 'Cash', 119);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (56, 'Milka Carletti', '01882770141', 'mcarletti2d@free.fr', 'Cash', 40);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (208, 'Bobbe Doherty', '03092646958', 'bdoherty2e@ihg.com', 'Ola Money', 210);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (172, 'Abbot Corrie', '05564693980', 'acorrie2f@joomla.org', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (49, 'Hedwig Curgenuer', '08911232032', 'hcurgenuer2g@smh.com.au', 'Ola Money', 204);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (110, 'Edin Starmore', '04239266589', 'estarmore2h@delicious.com', 'Cash', 185);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (64, 'Louisette Willgress', '09548992581', 'lwillgress2i@wired.com', 'Cash', 40);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (201, 'Melva Mc Dermid', '05998253212', 'mmc2j@g.co', 'Cash', 132);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (12, 'Allie Keher', '06198873972', 'akeher2k@adobe.com', 'Ola Money', 64);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (55, 'Cornie Krahl', '05775571927', 'ckrahl2l@constantcontact.com', 'Cash', 149);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (111, 'Pippa Lashmar', '01273934072', 'plashmar2m@marriott.com', 'Cash', 88);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (24, 'Rosette Ranklin', '05439551735', 'rranklin2n@clickbank.net', 'Ola Money', 120);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (121, 'Barth Buckthorpe', '05892159243', 'bbuckthorpe2o@woothemes.com', 'Ola Money', 188);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (91, 'Orelie Sinclaire', '07332659891', 'osinclaire2p@cbc.ca', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (207, 'Elisha McGougan', '09588855872', 'emcgougan2q@ameblo.jp', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (21, 'Harp Forber', '04084467858', 'hforber2r@rakuten.co.jp', 'Cash', 202);



insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (173, 'Georg McPartlin', '09277387635', 'gmcpartlin0@japanpost.jp', 'Ola Money', 92);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (204, 'Ula McCrackem', '07177024027', 'umccrackem1@qq.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (158, 'Orel Itzhak', '02538356827', 'oitzhak2@psu.edu', 'Ola Money', 128);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (221, 'Samaria Mesias', '06065456870', 'smesias3@slideshare.net', 'Cash', 182);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (182, 'Darby Zuann', '08656162726', 'dzuann4@unicef.org', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (56, 'Troy Guillond', '07572204979', 'tguillond5@sakura.ne.jp', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (64, 'Jamison Martynka', '02633068985', 'jmartynka6@fotki.com', 'Cash', 192);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (87, 'Stephanie Jacox', '09365871926', 'sjacox7@nba.com', 'Cash', 62);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (68, 'Kinna Templman', '02389129682', 'ktemplman8@paginegialle.it', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (48, 'Cybill Coning', '07335722301', 'cconing9@fastcompany.com', 'Cash', 210);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (40, 'Jen Stennine', '01799765551', 'jstenninea@google.es', 'Ola Money', 163);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (88, 'Vicki Huncoot', '08275473188', 'vhuncootb@ask.com', 'Cash', 130);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (153, 'Patience Whitloe', '08867167074', 'pwhitloec@wired.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (92, 'Nevile Duce', '04458301481', 'nduced@symantec.com', 'Ola Money', 40);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (131, 'Trudy Nelligan', '05031522710', 'tnelligane@dropbox.com', 'Cash', 219);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (144, 'Annmarie Imrie', '04987547359', 'aimrief@virginia.edu', 'Ola Money', 184);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (140, 'Hillary Jimmison', '04829077527', 'hjimmisong@thetimes.co.uk', 'Cash', 72);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (214, 'Gay Roston', '07378991056', 'grostonh@google.com.au', 'Cash', 212);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (20, 'Louisette Leheude', '07461351614', 'lleheudei@abc.net.au', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (165, 'Elaine Willcocks', '06128261189', 'ewillcocksj@geocities.jp', 'Cash', 217);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (192, 'Mil Phillip', '08638087537', 'mphillipk@senate.gov', 'Cash', 204);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (107, 'Thorndike Semorad', '09825363499', 'tsemoradl@netvibes.com', 'Cash', 178);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (216, 'Katharyn Mariotte', '09855628316', 'kmariottem@lycos.com', 'Cash', 7);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (124, 'Ardys Kenefick', '09633526593', 'akenefickn@foxnews.com', 'Cash', 194);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (113, 'Nicolas Heineke', '04172230902', 'nheinekeo@youtu.be', 'Ola Money', 141);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (80, 'Alika Ivoshin', '01955002353', 'aivoshinp@amazon.de', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (180, 'Dorian Pietzke', '01412477251', 'dpietzkeq@unicef.org', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (175, 'Costanza Giovannardi', '03935444935', 'cgiovannardir@sbwire.com', 'Cash', 200);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (11, 'Nikolia Casol', '01386711293', 'ncasols@sakura.ne.jp', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (178, 'Akim Rummer', '07429285064', 'arummert@bloglines.com', 'Ola Money', 36);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (165, 'Justine Ryam', '08039068525', 'jryamu@europa.eu', 'Ola Money', 102);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (128, 'Charlotta Lamlin', '01209986937', 'clamlinv@craigslist.org', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (163, 'Laurena O'' Mahony', '03068537590', 'low@wordpress.com', 'Ola Money', 83);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (121, 'Brooke Sanbroke', '03144763394', 'bsanbrokex@prnewswire.com', 'Cash', 166);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (99, 'Lalo Killimister', '09111646929', 'lkillimistery@reference.com', 'Cash', 2);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (203, 'Robinetta Loftie', '02398694061', 'rloftiez@nhs.uk', 'Ola Money', 88);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (178, 'Dyna Benian', '03155947836', 'dbenian10@tripadvisor.com', 'Ola Money', 171);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (131, 'Sandro Adriaan', '07147513897', 'sadriaan11@devhub.com', 'Ola Money', 15);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (61, 'Darryl Jozefowicz', '04188243268', 'djozefowicz12@unc.edu', 'Ola Money', 133);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (171, 'Ellie Eyres', '07022198287', 'eeyres13@yellowpages.com', 'Cash', 130);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (9, 'Ellen Boord', '09115476517', 'eboord14@networksolutions.com', 'Cash', 190);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (149, 'Carlie Whorf', '05231012711', 'cwhorf15@google.com.br', 'Cash', 39);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (100, 'Kirsten Alcott', '07127423489', 'kalcott16@icio.us', 'Ola Money', 52);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (201, 'Forbes Kerne', '01576771584', 'fkerne17@ning.com', 'Ola Money', 204);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (49, 'Jarvis Simeonov', '05399395423', 'jsimeonov18@de.vu', 'Ola Money', 120);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (8, 'Maureene Whittlesey', '03826638962', 'mwhittlesey19@mysql.com', 'Cash', 18);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (42, 'Lewie Tweed', '07731086044', 'ltweed1a@hhs.gov', 'Ola Money', 42);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (176, 'Tuesday Mathwen', '02942761394', 'tmathwen1b@redcross.org', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (23, 'Hamlin Kobke', '01565142292', 'hkobke1c@privacy.gov.au', 'Ola Money', 125);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (149, 'Lyndel Drissell', '09777187552', 'ldrissell1d@nhs.uk', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (28, 'Loise Broadway', '06494618807', 'lbroadway1e@boston.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (79, 'Adriena Golledge', '03252521303', 'agolledge1f@washington.edu', 'Ola Money', 37);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (6, 'Susanetta Sloat', '02544865445', 'ssloat1g@abc.net.au', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (165, 'Rockey Hasnip', '04357750158', 'rhasnip1h@twitpic.com', 'Cash', 152);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (215, 'Kipp Stedson', '02597261841', 'kstedson1i@java.com', 'Cash', 98);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (20, 'Arny Peacock', '08358432733', 'apeacock1j@howstuffworks.com', 'Ola Money', 35);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (87, 'Diandra Crothers', '05357955968', 'dcrothers1k@ning.com', 'Cash', 10);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (81, 'Iolanthe O''Carran', '09816080942', 'iocarran1l@artisteer.com', 'Ola Money', 125);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (158, 'Nisse Clampe', '04324663522', 'nclampe1m@loc.gov', 'Cash', 211);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (30, 'Alexis Lacey', '07589852700', 'alacey1n@washington.edu', 'Ola Money', 206);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (168, 'Bobbye Sutherby', '05258139479', 'bsutherby1o@1und1.de', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (3, 'Fianna Reignould', '02016807833', 'freignould1p@loc.gov', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (158, 'Bren Moseley', '09034469099', 'bmoseley1q@ebay.com', 'Cash', 5);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (8, 'Darya Paffot', '02799200331', 'dpaffot1r@bravesites.com', 'Ola Money', 111);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (44, 'Ase Scawn', '04626111911', 'ascawn1s@berkeley.edu', 'Cash', 50);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (9, 'Danya Grayland', '06525929207', 'dgrayland1t@wired.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (161, 'Zarah Galler', '02539989020', 'zgaller1u@ebay.com', 'Cash', 37);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (47, 'Noel Dunster', '09609844926', 'ndunster1v@comcast.net', 'Ola Money', 92);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (138, 'Mendel Siburn', '05105887193', 'msiburn1w@yolasite.com', 'Cash', 57);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (149, 'Kipper Champneys', '08311096054', 'kchampneys1x@wp.com', 'Cash', 166);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (153, 'Ker Phillimore', '03648253017', 'kphillimore1y@miitbeian.gov.cn', 'Ola Money', 138);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (123, 'Jennica Yurmanovev', '09311793614', 'jyurmanovev1z@imageshack.us', 'Ola Money', 207);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (85, 'Eleen Kynd', '03778837151', 'ekynd20@time.com', 'Ola Money', 90);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (215, 'Nelson Olliar', '09531457688', 'nolliar21@creativecommons.org', 'Cash', 83);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (94, 'Portia Aubray', '02845580567', 'paubray22@pen.io', 'Ola Money', 45);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (111, 'Sibella Sighart', '03206644803', 'ssighart23@blogger.com', 'Ola Money', 184);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (208, 'Cinderella Pizey', '03705414233', 'cpizey24@godaddy.com', 'Cash', 84);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (157, 'Duky Greenhall', '02968028328', 'dgreenhall25@ucla.edu', 'Cash', 133);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (37, 'Michaeline Shipcott', '04253593443', 'mshipcott26@digg.com', 'Cash', 182);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (104, 'Derry Revie', '07848414932', 'drevie27@ucla.edu', 'Ola Money', 151);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (117, 'Aggy Furze', '07231308537', 'afurze28@omniture.com', 'Ola Money', 51);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (46, 'Bertrando Mosedall', '03592225224', 'bmosedall29@purevolume.com', 'Ola Money', 205);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (55, 'Jennie Denisovo', '06171421048', 'jdenisovo2a@drupal.org', 'Ola Money', 68);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (2, 'Latrena Lodden', '05829896123', 'llodden2b@hatena.ne.jp', 'Ola Money', 137);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (43, 'Renato Brophy', '05008151028', 'rbrophy2c@nyu.edu', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (145, 'Ricca Dobney', '09491950729', 'rdobney2d@ucla.edu', 'Cash', 141);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (82, 'Tristan Flaws', '04237374422', 'tflaws2e@biblegateway.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (20, 'Eduard Attiwill', '09855032604', 'eattiwill2f@ehow.com', 'Cash', 44);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (97, 'Faulkner Casassa', '07253775747', 'fcasassa2g@hubpages.com', 'Cash', 224);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (77, 'Skyler Mackiewicz', '01992068661', 'smackiewicz2h@yandex.ru', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (56, 'Mabel Cawdron', '05122085580', 'mcawdron2i@patch.com', 'Ola Money', 77);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (134, 'Laney Harraway', '07498906894', 'lharraway2j@timesonline.co.uk', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (114, 'Barnett MacVagh', '06195068914', 'bmacvagh2k@ow.ly', 'Cash', 89);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (169, 'Rickert Cuttin', '08246106474', 'rcuttin2l@cbc.ca', 'Cash', 216);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (114, 'Lyn Godlonton', '02656225074', 'lgodlonton2m@rambler.ru', 'Cash', 176);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (23, 'Maurizia Aslett', '03791326278', 'maslett2n@bloomberg.com', 'Cash', 187);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (44, 'Perrine Cropton', '02997480103', 'pcropton2o@drupal.org', 'Cash', 168);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (126, 'Sibilla Awmack', '06664614190', 'sawmack2p@hibu.com', 'Ola Money', 173);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (167, 'Ameline Gulleford', '08716011482', 'agulleford2q@ft.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (19, 'Nevil Andreu', '06186768835', 'nandreu2r@rambler.ru', 'Cash', 64);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (177, 'Madlen Preon', '02632512735', 'mpreon2s@reddit.com', 'Ola Money', 78);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (177, 'Clary Jump', '01014196295', 'cjump2t@phpbb.com', 'Ola Money', 154);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (3, 'Freeman Riceards', '04388360344', 'friceards2u@skype.com', 'Ola Money', 80);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (33, 'Conn Brombell', '03781598453', 'cbrombell2v@instagram.com', 'Ola Money', 208);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (65, 'Wallie Elfes', '03196627954', 'welfes2w@sun.com', 'Ola Money', 16);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (60, 'Marie-ann Attard', '07903720190', 'mattard2x@discuz.net', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (60, 'Zabrina Brinkley', '03744151917', 'zbrinkley2y@booking.com', 'Cash', 58);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (104, 'Jessica McAloren', '07034477756', 'jmcaloren2z@odnoklassniki.ru', 'Ola Money', 175);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (126, 'Hadrian Biggadike', '03703966571', 'hbiggadike30@tmall.com', 'Cash', 194);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (6, 'Kore Ossulton', '04331775739', 'kossulton31@abc.net.au', 'Ola Money', 150);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (217, 'Vivianne Ralton', '02372969946', 'vralton32@delicious.com', 'Cash', 36);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (126, 'Terencio Steptoe', '09417048194', 'tsteptoe33@miibeian.gov.cn', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (75, 'Mario Collumbell', '05476435275', 'mcollumbell34@skype.com', 'Cash', 86);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (224, 'Felix Dossit', '08847318883', 'fdossit35@foxnews.com', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (60, 'Jenilee Robic', '05867036411', 'jrobic36@multiply.com', 'Ola Money', 127);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (113, 'Anatol Grasser', '09405671909', 'agrasser37@ehow.com', 'Cash', 98);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (26, 'Florette Sellens', '09164547221', 'fsellens38@last.fm', 'Ola Money', 109);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (123, 'Roman Kilcoyne', '03177854397', 'rkilcoyne39@google.cn', null, null);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (16, 'Shena Strettle', '04176389402', 'sstrettle3a@aol.com', 'Ola Money', 173);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (94, 'Haywood Kitcherside', '07071430299', 'hkitcherside3b@house.gov', 'Ola Money', 118);
insert into customers (location_id, name, contact, emailid, paymentmode, savedplace1) values (189, 'Gaspard Lownes', '05342225888', 'glownes3c@google.cn', 'Ola Money', 96);

