insert into location (street, locality, city, state, pincode) values ('3 Graceland Street', 'Linden', 'New Delhi', 'Delhi', 110010);
insert into location (street, locality, city, state, pincode) values ('046 Sycamore Avenue', 'Thackeray', 'New Delhi', 'Delhi', 110064);
insert into location (street, locality, city, state, pincode) values ('1972 Dennis Junction', 'Oneill', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('39 Bluejay Terrace', 'Monument', 'New Delhi', 'Delhi', 110068);
insert into location (street, locality, city, state, pincode) values ('50080 Dapin Road', 'Elmside', 'New Delhi', 'Delhi', 110012);
insert into location (street, locality, city, state, pincode) values ('0 Northland Plaza', 'Rieder', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('1040 Dennis Way', 'Sachs', 'New Delhi', 'Delhi', 110032);
insert into location (street, locality, city, state, pincode) values ('099 Myrtle Junction', 'Eggendart', 'New Delhi', 'Delhi', 110031);
insert into location (street, locality, city, state, pincode) values ('4202 Dexter Junction', 'Glacier Hill', 'New Delhi', 'Delhi', 110038);
insert into location (street, locality, city, state, pincode) values ('68158 Anniversary Terrace', 'Kedzie', 'New Delhi', 'Delhi', 110030);
insert into location (street, locality, city, state, pincode) values ('30 Oneill Place', 'Mandrake', 'New Delhi', 'Delhi', 110019);
insert into location (street, locality, city, state, pincode) values ('0861 Victoria Court', 'Heath', 'New Delhi', 'Delhi', 110046);
insert into location (street, locality, city, state, pincode) values ('1 Transport Junction', 'Summit', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('52334 Glacier Hill Avenue', 'Eliot', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('50617 Roth Point', 'Sloan', 'New Delhi', 'Delhi', 110004);
insert into location (street, locality, city, state, pincode) values ('2864 Green Plaza', 'Alpine', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('61700 Fisk Alley', 'Main', 'New Delhi', 'Delhi', 110005);
insert into location (street, locality, city, state, pincode) values ('754 Killdeer Pass', 'Blaine', 'New Delhi', 'Delhi', 110032);
insert into location (street, locality, city, state, pincode) values ('835 Merry Drive', 'Delaware', 'New Delhi', 'Delhi', 110046);
insert into location (street, locality, city, state, pincode) values ('502 Messerschmidt Junction', 'Mosinee', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('8 Jackson Court', 'Hovde', 'New Delhi', 'Delhi', 110004);
insert into location (street, locality, city, state, pincode) values ('837 Blaine Court', 'Sauthoff', 'New Delhi', 'Delhi', 110018);
insert into location (street, locality, city, state, pincode) values ('0569 Barnett Drive', '7th', 'New Delhi', 'Delhi', 110067);
insert into location (street, locality, city, state, pincode) values ('0 North Street', 'Northland', 'New Delhi', 'Delhi', 110014);
insert into location (street, locality, city, state, pincode) values ('31400 Warrior Avenue', 'Birchwood', 'New Delhi', 'Delhi', 110034);
insert into location (street, locality, city, state, pincode) values ('8203 Namekagon Place', 'Magdeline', 'New Delhi', 'Delhi', 110049);
insert into location (street, locality, city, state, pincode) values ('79609 Randy Point', 'Talmadge', 'New Delhi', 'Delhi', 110019);
insert into location (street, locality, city, state, pincode) values ('68 Reinke Drive', 'Saint Paul', 'New Delhi', 'Delhi', 110026);
insert into location (street, locality, city, state, pincode) values ('90159 Stoughton Drive', 'Stoughton', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('9 School Road', 'American Ash', 'New Delhi', 'Delhi', 110068);
insert into location (street, locality, city, state, pincode) values ('55278 Victoria Parkway', 'Caliangt', 'New Delhi', 'Delhi', 110048);
insert into location (street, locality, city, state, pincode) values ('7 American Ash Hill', 'Lerdahl', 'New Delhi', 'Delhi', 110056);
insert into location (street, locality, city, state, pincode) values ('4 Bobwhite Terrace', 'Corry', 'New Delhi', 'Delhi', 110033);
insert into location (street, locality, city, state, pincode) values ('180 Sycamore Plaza', 'Bultman', 'New Delhi', 'Delhi', 110003);
insert into location (street, locality, city, state, pincode) values ('3 Logan Pass', 'Fisk', 'New Delhi', 'Delhi', 110041);
insert into location (street, locality, city, state, pincode) values ('41529 Union Way', 'Parkside', 'New Delhi', 'Delhi', 110052);
insert into location (street, locality, city, state, pincode) values ('30 Waubesa Avenue', 'Sherman', 'New Delhi', 'Delhi', 110058);
insert into location (street, locality, city, state, pincode) values ('06 Sachtjen Place', 'Sommers', 'New Delhi', 'Delhi', 110026);
insert into location (street, locality, city, state, pincode) values ('132 Bartelt Way', 'Sunbrook', 'New Delhi', 'Delhi', 110042);
insert into location (street, locality, city, state, pincode) values ('1998 Susan Junction', 'Hovde', 'New Delhi', 'Delhi', 110004);
insert into location (street, locality, city, state, pincode) values ('10072 Banding Way', 'Elmside', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('30095 Havey Plaza', '7th', 'New Delhi', 'Delhi', 110065);
insert into location (street, locality, city, state, pincode) values ('8 Weeping Birch Avenue', 'Upham', 'New Delhi', 'Delhi', 110042);
insert into location (street, locality, city, state, pincode) values ('36591 Hovde Street', 'Iowa', 'New Delhi', 'Delhi', 110005);
insert into location (street, locality, city, state, pincode) values ('089 Calypso Terrace', 'Service', 'New Delhi', 'Delhi', 110066);
insert into location (street, locality, city, state, pincode) values ('0 Anhalt Trail', 'Gulseth', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('5 Weeping Birch Pass', 'Schiller', 'New Delhi', 'Delhi', 110047);
insert into location (street, locality, city, state, pincode) values ('209 Pepper Wood Way', 'Westridge', 'New Delhi', 'Delhi', 110012);
insert into location (street, locality, city, state, pincode) values ('80591 Eagan Alley', 'Ilene', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('7 Norway Maple Crossing', 'Nobel', 'New Delhi', 'Delhi', 110061);
insert into location (street, locality, city, state, pincode) values ('64 Miller Pass', 'North', 'New Delhi', 'Delhi', 110068);
insert into location (street, locality, city, state, pincode) values ('43483 Nancy Park', 'Moulton', 'New Delhi', 'Delhi', 110018);
insert into location (street, locality, city, state, pincode) values ('005 Sommers Crossing', 'Debra', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('5 Beilfuss Court', 'Fuller', 'New Delhi', 'Delhi', 110038);
insert into location (street, locality, city, state, pincode) values ('41165 Crest Line Alley', 'Hauk', 'New Delhi', 'Delhi', 110061);
insert into location (street, locality, city, state, pincode) values ('6122 Twin Pines Drive', 'Kings', 'New Delhi', 'Delhi', 110013);
insert into location (street, locality, city, state, pincode) values ('2 Barnett Crossing', 'Mifflin', 'New Delhi', 'Delhi', 110020);
insert into location (street, locality, city, state, pincode) values ('2 Moose Place', 'Macpherson', 'New Delhi', 'Delhi', 110052);
insert into location (street, locality, city, state, pincode) values ('5 Raven Drive', 'Utah', 'New Delhi', 'Delhi', 110049);
insert into location (street, locality, city, state, pincode) values ('9 Park Meadow Hill', 'Manufacturers', 'New Delhi', 'Delhi', 110003);
insert into location (street, locality, city, state, pincode) values ('96795 Kedzie Lane', 'Lukken', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('9 Grover Court', 'Granby', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('627 Mariners Cove Terrace', 'Judy', 'New Delhi', 'Delhi', 110063);
insert into location (street, locality, city, state, pincode) values ('669 Cambridge Parkway', 'Pankratz', 'New Delhi', 'Delhi', 110016);
insert into location (street, locality, city, state, pincode) values ('0727 Valley Edge Junction', 'Merry', 'New Delhi', 'Delhi', 110043);
insert into location (street, locality, city, state, pincode) values ('60434 Golf Course Pass', 'Blue Bill Park', 'New Delhi', 'Delhi', 110050);
insert into location (street, locality, city, state, pincode) values ('9875 Summerview Drive', 'Fairview', 'New Delhi', 'Delhi', 110025);
insert into location (street, locality, city, state, pincode) values ('7528 Goodland Alley', 'Messerschmidt', 'New Delhi', 'Delhi', 110025);
insert into location (street, locality, city, state, pincode) values ('0 Corry Plaza', 'Fulton', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('52999 Birchwood Way', 'Ilene', 'New Delhi', 'Delhi', 110011);
insert into location (street, locality, city, state, pincode) values ('9 Sunbrook Lane', 'Logan', 'New Delhi', 'Delhi', 110048);
insert into location (street, locality, city, state, pincode) values ('7 Luster Place', 'Ronald Regan', 'New Delhi', 'Delhi', 110032);
insert into location (street, locality, city, state, pincode) values ('975 Dryden Junction', '3rd', 'New Delhi', 'Delhi', 110062);
insert into location (street, locality, city, state, pincode) values ('9347 Drewry Street', 'Evergreen', 'New Delhi', 'Delhi', 110045);
insert into location (street, locality, city, state, pincode) values ('01836 Basil Center', 'Merrick', 'New Delhi', 'Delhi', 110020);
insert into location (street, locality, city, state, pincode) values ('3042 Paget Crossing', 'Laurel', 'New Delhi', 'Delhi', 110007);
insert into location (street, locality, city, state, pincode) values ('02 Becker Crossing', 'Quincy', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('2 Shopko Place', '3rd', 'New Delhi', 'Delhi', 110046);
insert into location (street, locality, city, state, pincode) values ('91 Londonderry Pass', 'Hintze', 'New Delhi', 'Delhi', 110034);
insert into location (street, locality, city, state, pincode) values ('18545 Texas Point', 'David', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('991 Brickson Park Circle', 'Gulseth', 'New Delhi', 'Delhi', 110051);
insert into location (street, locality, city, state, pincode) values ('6 Doe Crossing Alley', 'Shoshone', 'New Delhi', 'Delhi', 110063);
insert into location (street, locality, city, state, pincode) values ('723 Charing Cross Point', 'Killdeer', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('555 David Trail', 'Iowa', 'New Delhi', 'Delhi', 110014);
insert into location (street, locality, city, state, pincode) values ('19 Judy Park', 'Linden', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('50 Union Parkway', 'Judy', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('1090 Fairfield Plaza', 'Crescent Oaks', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('8 Portage Plaza', 'Independence', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('08792 Evergreen Place', 'Union', 'New Delhi', 'Delhi', 110043);
insert into location (street, locality, city, state, pincode) values ('8517 Schurz Junction', 'Debra', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('54 Macpherson Junction', 'Thierer', 'New Delhi', 'Delhi', 110041);
insert into location (street, locality, city, state, pincode) values ('28 Pawling Drive', 'Gerald', 'New Delhi', 'Delhi', 110024);
insert into location (street, locality, city, state, pincode) values ('6 Glendale Drive', 'Talisman', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('1 Ludington Street', 'Waubesa', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('981 Park Meadow Park', 'Kings', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('26817 Northview Place', 'Main', 'New Delhi', 'Delhi', 110070);
insert into location (street, locality, city, state, pincode) values ('343 Crownhardt Circle', 'Crownhardt', 'New Delhi', 'Delhi', 110030);
insert into location (street, locality, city, state, pincode) values ('01534 Michigan Place', 'Center', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('51100 Crownhardt Junction', 'Porter', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);


insert into location (street, locality, city, state, pincode) values ('922 Declaration Place', 'Melvin', 'Mathura', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('841 Laurel Crossing', 'Orin', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220046);
insert into location (street, locality, city, state, pincode) values ('8 Glendale Center', 'Jackson', 'Agra', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('05 Evergreen Way', 'Everett', 'Meerut', 'Uttar Pradesh', 220022);
insert into location (street, locality, city, state, pincode) values ('8 Katie Road', 'Northridge', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220072);
insert into location (street, locality, city, state, pincode) values ('0829 Myrtle Crossing', 'Ramsey', 'Agra', 'Uttar Pradesh', 220020);
insert into location (street, locality, city, state, pincode) values ('8361 Packers Hill', 'Elgar', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('09167 Eagan Pass', 'Bunting', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220072);
insert into location (street, locality, city, state, pincode) values ('19377 Bonner Plaza', 'Marquette', 'Mathura', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('812 Drewry Junction', 'South', 'Mathura', 'Uttar Pradesh', 220047);
insert into location (street, locality, city, state, pincode) values ('0771 Mallory Park', 'Eggendart', 'Vrindavan', 'Uttar Pradesh', 220024);
insert into location (street, locality, city, state, pincode) values ('2132 Dennis Hill', 'Coolidge', 'Meerut', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('73719 Main Terrace', 'Boyd', 'Ghaziabad', 'Uttar Pradesh', 220015);
insert into location (street, locality, city, state, pincode) values ('6722 Bultman Road', 'Hoepker', 'Mathura', 'Uttar Pradesh', 220040);
insert into location (street, locality, city, state, pincode) values ('0 Florence Parkway', 'Shoshone', 'Vrindavan', 'Uttar Pradesh', 220077);
insert into location (street, locality, city, state, pincode) values ('48443 Summer Ridge Road', 'Fulton', 'Ghaziabad', 'Uttar Pradesh', 220079);
insert into location (street, locality, city, state, pincode) values ('0 Beilfuss Point', 'Ridge Oak', 'Vrindavan', 'Uttar Pradesh', 220050);
insert into location (street, locality, city, state, pincode) values ('1 8th Road', 'Springs', 'Meerut', 'Uttar Pradesh', 220021);
insert into location (street, locality, city, state, pincode) values ('42 Springs Street', 'Rigney', 'Ghaziabad', 'Uttar Pradesh', 220076);
insert into location (street, locality, city, state, pincode) values ('42448 Sachs Hill', 'Talmadge', 'Vrindavan', 'Uttar Pradesh', 220014);
insert into location (street, locality, city, state, pincode) values ('57412 Debs Circle', 'Crowley', 'Ghaziabad', 'Uttar Pradesh', 220009);
insert into location (street, locality, city, state, pincode) values ('434 Hayes Avenue', 'Mallard', 'Mathura', 'Uttar Pradesh', 220055);
insert into location (street, locality, city, state, pincode) values ('203 Sachtjen Crossing', 'Merrick', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220072);
insert into location (street, locality, city, state, pincode) values ('9 Monica Road', 'Dwight', 'Mathura', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('7786 Debra Crossing', 'Lakewood Gardens', 'Mathura', 'Uttar Pradesh', 220042);
insert into location (street, locality, city, state, pincode) values ('839 Sullivan Street', 'Mockingbird', 'Agra', 'Uttar Pradesh', 220015);
insert into location (street, locality, city, state, pincode) values ('4568 Menomonie Avenue', 'Morning', 'Meerut', 'Uttar Pradesh', 220011);
insert into location (street, locality, city, state, pincode) values ('11 Oriole Crossing', 'Main', 'Meerut', 'Uttar Pradesh', 220048);
insert into location (street, locality, city, state, pincode) values ('52987 Mcguire Terrace', 'Fair Oaks', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220043);
insert into location (street, locality, city, state, pincode) values ('5 Namekagon Center', 'Veith', 'Vrindavan', 'Uttar Pradesh', 220040);
insert into location (street, locality, city, state, pincode) values ('0404 Messerschmidt Way', 'Summer Ridge', 'Mathura', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('5 Vernon Trail', 'Orin', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220005);
insert into location (street, locality, city, state, pincode) values ('17857 Morningstar Terrace', 'Brentwood', 'Ghaziabad', 'Uttar Pradesh', 220068);
insert into location (street, locality, city, state, pincode) values ('912 Waxwing Hill', 'Division', 'Meerut', 'Uttar Pradesh', 220018);
insert into location (street, locality, city, state, pincode) values ('398 Oriole Road', 'Basil', 'Vrindavan', 'Uttar Pradesh', 220036);
insert into location (street, locality, city, state, pincode) values ('6664 Heath Hill', 'Anzinger', 'Ghaziabad', 'Uttar Pradesh', 220004);
insert into location (street, locality, city, state, pincode) values ('4 Sommers Alley', 'Reinke', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('195 Holmberg Crossing', 'Hayes', 'Vrindavan', 'Uttar Pradesh', 220039);
insert into location (street, locality, city, state, pincode) values ('27732 Briar Crest Alley', 'Westerfield', 'Ghaziabad', 'Uttar Pradesh', 220007);
insert into location (street, locality, city, state, pincode) values ('375 Bultman Avenue', 'Rieder', 'Mathura', 'Uttar Pradesh', 220010);
insert into location (street, locality, city, state, pincode) values ('5992 Dovetail Circle', 'Oriole', 'Meerut', 'Uttar Pradesh', 220056);
insert into location (street, locality, city, state, pincode) values ('4 Sunbrook Point', 'Continental', 'Mathura', 'Uttar Pradesh', 220033);
insert into location (street, locality, city, state, pincode) values ('4551 Gateway Lane', 'Gina', 'Ghaziabad', 'Uttar Pradesh', 220035);
insert into location (street, locality, city, state, pincode) values ('32 Riverside Center', 'Morningstar', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220054);
insert into location (street, locality, city, state, pincode) values ('2 West Terrace', 'Roxbury', 'Meerut', 'Uttar Pradesh', 220071);
insert into location (street, locality, city, state, pincode) values ('44 Nobel Way', 'Atwood', 'Meerut', 'Uttar Pradesh', 220005);
insert into location (street, locality, city, state, pincode) values ('1 Anderson Court', 'American Ash', 'Meerut', 'Uttar Pradesh', 220030);
insert into location (street, locality, city, state, pincode) values ('6530 Merry Avenue', 'Loeprich', 'Agra', 'Uttar Pradesh', 220031);
insert into location (street, locality, city, state, pincode) values ('63860 Clarendon Center', 'Buhler', 'Vrindavan', 'Uttar Pradesh', 220010);
insert into location (street, locality, city, state, pincode) values ('97 Sheridan Hill', 'Westerfield', 'Meerut', 'Uttar Pradesh', 220030);
insert into location (street, locality, city, state, pincode) values ('2809 Schmedeman Avenue', 'Charing Cross', 'Ghaziabad', 'Uttar Pradesh', 220065);
insert into location (street, locality, city, state, pincode) values ('456 Moose Center', 'Blackbird', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220041);
insert into location (street, locality, city, state, pincode) values ('12 Stuart Point', 'Aberg', 'Mathura', 'Uttar Pradesh', 220078);
insert into location (street, locality, city, state, pincode) values ('5874 Dennis Terrace', 'Heffernan', 'Meerut', 'Uttar Pradesh', 220030);
insert into location (street, locality, city, state, pincode) values ('8025 Gale Way', 'Moulton', 'Meerut', 'Uttar Pradesh', 220006);
insert into location (street, locality, city, state, pincode) values ('97 Raven Drive', 'Ryan', 'Meerut', 'Uttar Pradesh', 220064);
insert into location (street, locality, city, state, pincode) values ('83 Morning Lane', 'Everett', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220018);
insert into location (street, locality, city, state, pincode) values ('6 Birchwood Junction', 'Nova', 'Agra', 'Uttar Pradesh', 220076);
insert into location (street, locality, city, state, pincode) values ('982 Algoma Plaza', 'Green Ridge', 'Vrindavan', 'Uttar Pradesh', 220040);
insert into location (street, locality, city, state, pincode) values ('23643 Schurz Drive', 'Saint Paul', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220032);
insert into location (street, locality, city, state, pincode) values ('26 Vahlen Trail', 'Michigan', 'Agra', 'Uttar Pradesh', 220060);
insert into location (street, locality, city, state, pincode) values ('34 Sunnyside Street', 'Farragut', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('63 Sundown Court', 'Veith', 'Mathura', 'Uttar Pradesh', 220007);
insert into location (street, locality, city, state, pincode) values ('16 Waxwing Place', 'Dwight', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('3 Mariners Cove Crossing', 'Hintze', 'Meerut', 'Uttar Pradesh', 220061);
insert into location (street, locality, city, state, pincode) values ('048 Browning Center', 'Arrowood', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220032);
insert into location (street, locality, city, state, pincode) values ('495 Badeau Crossing', 'Mallard', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('8 Shasta Lane', 'Scott', 'Ghaziabad', 'Uttar Pradesh', 220028);
insert into location (street, locality, city, state, pincode) values ('9 Brentwood Parkway', 'Lindbergh', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220058);
insert into location (street, locality, city, state, pincode) values ('5 Donald Drive', 'Kennedy', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220006);
insert into location (street, locality, city, state, pincode) values ('0 Jenna Point', 'Hallows', 'Ghaziabad', 'Uttar Pradesh', 220029);
insert into location (street, locality, city, state, pincode) values ('90604 Russell Alley', 'Badeau', 'Ghaziabad', 'Uttar Pradesh', 220068);
insert into location (street, locality, city, state, pincode) values ('69538 Helena Pass', 'Dwight', 'Mathura', 'Uttar Pradesh', 220056);
insert into location (street, locality, city, state, pincode) values ('2 Garrison Street', 'Gulseth', 'Agra', 'Uttar Pradesh', 220029);
insert into location (street, locality, city, state, pincode) values ('42 Wayridge Drive', 'Maryland', 'Ghaziabad', 'Uttar Pradesh', 220026);
insert into location (street, locality, city, state, pincode) values ('6 Hollow Ridge Way', 'Bellgrove', 'Ghaziabad', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('104 Loomis Plaza', 'Heath', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220037);
insert into location (street, locality, city, state, pincode) values ('9 Redwing Circle', 'Farwell', 'Meerut', 'Uttar Pradesh', 220058);
insert into location (street, locality, city, state, pincode) values ('69 Hermina Court', 'Hoard', 'Vrindavan', 'Uttar Pradesh', 220075);
insert into location (street, locality, city, state, pincode) values ('484 Ludington Circle', 'Sutherland', 'Agra', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('62595 Swallow Place', 'Marcy', 'Agra', 'Uttar Pradesh', 220049);
insert into location (street, locality, city, state, pincode) values ('6134 Northwestern Point', 'Shopko', 'Vrindavan', 'Uttar Pradesh', 220068);
insert into location (street, locality, city, state, pincode) values ('58974 Fieldstone Lane', 'Florence', 'Agra', 'Uttar Pradesh', 220044);
insert into location (street, locality, city, state, pincode) values ('78924 Bellgrove Avenue', 'Washington', 'Vrindavan', 'Uttar Pradesh', 220073);
insert into location (street, locality, city, state, pincode) values ('5142 Atwood Lane', 'Delaware', 'Meerut', 'Uttar Pradesh', 220062);
insert into location (street, locality, city, state, pincode) values ('31 Clyde Gallagher Park', 'West', 'Ghaziabad', 'Uttar Pradesh', 220051);
insert into location (street, locality, city, state, pincode) values ('20 Warbler Trail', 'Fairview', 'Vrindavan', 'Uttar Pradesh', 220003);
insert into location (street, locality, city, state, pincode) values ('5 Grim Drive', 'Elka', 'Vrindavan', 'Uttar Pradesh', 220065);
insert into location (street, locality, city, state, pincode) values ('79567 Melody Drive', 'Dorton', 'Agra', 'Uttar Pradesh', 220054);
insert into location (street, locality, city, state, pincode) values ('06 Old Gate Park', 'Hintze', 'Agra', 'Uttar Pradesh', 220034);
insert into location (street, locality, city, state, pincode) values ('28820 Ridgeway Alley', 'Granby', 'Mathura', 'Uttar Pradesh', 220035);
insert into location (street, locality, city, state, pincode) values ('38047 Amoth Crossing', 'Artisan', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220052);
insert into location (street, locality, city, state, pincode) values ('883 Northview Parkway', 'Anzinger', 'Mathura', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('664 Lyons Terrace', 'Ridgeview', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220065);
insert into location (street, locality, city, state, pincode) values ('921 Dayton Terrace', 'Bunker Hill', 'Vrindavan', 'Uttar Pradesh', 220012);
insert into location (street, locality, city, state, pincode) values ('937 Pierstorff Place', 'Troy', 'Ghaziabad', 'Uttar Pradesh', 220080);
insert into location (street, locality, city, state, pincode) values ('50 Summit Drive', 'Laurel', 'Meerut', 'Uttar Pradesh', 220027);
insert into location (street, locality, city, state, pincode) values ('0 Farwell Point', 'Del Mar', 'Gautam Buddh Nagar', 'Uttar Pradesh', 220050);
insert into location (street, locality, city, state, pincode) values ('43220 Schlimgen Way', 'Carioca', 'Ghaziabad', 'Uttar Pradesh', 220043);
insert into location (street, locality, city, state, pincode) values ('20007 Dexter Drive', 'Kenwood', 'Mathura', 'Uttar Pradesh', 220079);






insert into location (street, locality, city, state, pincode) values ('18545 Texas Point', 'David', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('991 Brickson Park Circle', 'Gulseth', 'New Delhi', 'Delhi', 110051);
insert into location (street, locality, city, state, pincode) values ('6 Doe Crossing Alley', 'Shoshone', 'New Delhi', 'Delhi', 110063);
insert into location (street, locality, city, state, pincode) values ('723 Charing Cross Point', 'Killdeer', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('555 David Trail', 'Iowa', 'New Delhi', 'Delhi', 110014);
insert into location (street, locality, city, state, pincode) values ('19 Judy Park', 'Linden', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('50 Union Parkway', 'Judy', 'New Delhi', 'Delhi', 110053);
insert into location (street, locality, city, state, pincode) values ('1090 Fairfield Plaza', 'Crescent Oaks', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('8 Portage Plaza', 'Independence', 'New Delhi', 'Delhi', 110040);
insert into location (street, locality, city, state, pincode) values ('08792 Evergreen Place', 'Union', 'New Delhi', 'Delhi', 110043);
insert into location (street, locality, city, state, pincode) values ('8517 Schurz Junction', 'Debra', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('54 Macpherson Junction', 'Thierer', 'New Delhi', 'Delhi', 110041);
insert into location (street, locality, city, state, pincode) values ('28 Pawling Drive', 'Gerald', 'New Delhi', 'Delhi', 110024);
insert into location (street, locality, city, state, pincode) values ('6 Glendale Drive', 'Talisman', 'New Delhi', 'Delhi', 110002);
insert into location (street, locality, city, state, pincode) values ('1 Ludington Street', 'Waubesa', 'New Delhi', 'Delhi', 110001);
insert into location (street, locality, city, state, pincode) values ('981 Park Meadow Park', 'Kings', 'New Delhi', 'Delhi', 110055);
insert into location (street, locality, city, state, pincode) values ('26817 Northview Place', 'Main', 'New Delhi', 'Delhi', 110070);
insert into location (street, locality, city, state, pincode) values ('343 Crownhardt Circle', 'Crownhardt', 'New Delhi', 'Delhi', 110030);
insert into location (street, locality, city, state, pincode) values ('01534 Michigan Place', 'Center', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('51100 Crownhardt Junction', 'Porter', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('01534 Michigan Place', 'Center', 'New Delhi', 'Delhi', 110006);
insert into location (street, locality, city, state, pincode) values ('51100 Crownhardt Junction', 'Porter', 'New Delhi', 'Delhi', 110035);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);
insert into location (street, locality, city, state, pincode) values ('0515 Kenwood Circle', 'Maple', 'New Delhi', 'Delhi', 110057);

